// Auto-generated by LibreLane
module ffram(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input[31:0] d_in,
  input[31:0] bit_en,
  input[6:0] addr,
  input rst,
  input clk,
  input wb_en,
  input r_en,
  output[31:0] d_out
);
endmodule
